export const navData = [
  {
    title: '运维中心',
    icon: 'emicon-jiqunguanli',
    code: 'menu_ops_center',
    url: '/opscenter',
    level: 'first',
    routers: [
      '/opscenter/overview',
      '/opscenter/service',
      '/opscenter/hoststatus',
      'sub_menu_diagnose',
    ],
    children: [
      {
        title: '概览',
        icon: 'emicon-gailan',
        code: 'sub_menu_overview',
        url: '/opscenter/overview',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '服务',
        icon: 'emicon-fuwu',
        code: 'sub_menu_service',
        url: '/opscenter/service',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '主机',
        icon: 'emicon-zhuji',
        code: 'sub_menu_host',
        url: '/opscenter/hoststatus',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '诊断',
        icon: 'emicon-zhenduan',
        code: 'sub_menu_diagnose',
        url: '/opscenter/diagnosis',
        level: 'second',
        routers: [
          '/opscenter/diagnosis/log',
          '/opscenter/diagnosis/event',
          '/opscenter/diagnosis/config',
          '/opscenter/diagnosis/inspectionReport',
          '/opscenter/diagnosis/backup',
        ],
        children: [
          {
            title: '日志查看',
            icon: 'emicon-rizhichakan',
            code: 'sub_menu_diagnose_log',
            url: '/opscenter/diagnosis/log',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '事件诊断',
            icon: 'emicon-shijianzhenduan',
            code: 'sub_menu_diagnose_event',
            url: '/opscenter/diagnosis/event',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '配置变更',
            icon: 'emicon-peizhibiangeng',
            code: 'sub_menu_diagnose_config_change',
            url: '/opscenter/diagnosis/config',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '巡检报告',
            icon: 'emicon-xunjianbaogao',
            code: 'sub_menu_diagnose',
            url: '/opscenter/diagnosis/inspectionReport',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '备份管理',
            icon: 'emicon-beifenguanli',
            code: 'sub_menu_diagnose_backup',
            url: '/opscenter/diagnosis/backup',
            level: 'three',
            routers: [],
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: '部署中心',
    icon: 'emicon-yingyongguanli',
    code: 'menu_deploy_center',
    url: '/deploycenter',
    level: 'first',
    routers: [
      '/deploycenter/cluster',
      '/deploycenter/appmanage',
      '/deploycenter/deployed',
    ],
    children: [
      {
        title: '集群管理',
        icon: 'emicon-jiqunguanli1',
        code: 'sub_menu_cluster_manage',
        url: '/deploycenter/cluster',
        level: 'second',
        routers: [
          '/deploycenter/cluster/list',
          '/deploycenter/cluster/create',
          '/deploycenter/cluster/create/edit',
          '/deploycenter/cluster/create/add',
          '/deploycenter/cluster/detail/index',
          '/deploycenter/cluster/detail/host',
          '/deploycenter/cluster/detail/imagestore',
          '/deploycenter/cluster/detail/namespace',
          '/deploycenter/cluster/detail/deployed',
          '/deploycenter/cluster/detail/history',
          '/deploycenter/cluster/detail/patchHistory',
          '/deploycenter/cluster/detail/echoList',
          '/deploycenter/cluster/detail/echoDetail',
        ],
        children: [
          {
            title: '集群列表',
            icon: 'emicon-rizhichakan',
            code: 'sub_menu_cluster_list',
            url: '/deploycenter/cluster/list',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '添加集群',
            icon: 'emicon-shijianzhenduan',
            code: 'sub_menu_cluster_edit',
            url: '/deploycenter/cluster/create',
            level: 'three',
            routers: [],
            children: [],
          },
        ],
      },
      {
        title: '组件管理',
        icon: 'emicon-zujianguanli',
        code: 'sub_menu_product_manage',
        url: '/deploycenter/appmanage',
        level: 'second',
        routers: [
          '/deploycenter/appmanage/products',
          '/deploycenter/appmanage/installs',
        ],
        children: [
          {
            title: '组件列表',
            icon: 'emicon-rizhichakan',
            code: 'sub_menu_product_list',
            url: '/deploycenter/appmanage/products',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '部署组件',
            icon: 'emicon-shijianzhenduan',
            code: 'sub_menu_product_deploy',
            url: '/deploycenter/appmanage/installs',
            level: 'three',
            routers: [],
            children: [],
          },
        ],
      },
      {
        title: '告警监控',
        icon: 'emicon-jiankonggaojing2',
        code: 'sub_menu_monitor',
        url: '/deploycenter/deployed',
        level: 'second',
        routers: [
          '/deploycenter/monitoring/dashboard',
          '/deploycenter/monitoring/dashdetail',
          '/deploycenter/monitoring/alert',
          '/deploycenter/monitoring/addAlert',
        ],
        children: [
          {
            title: '仪表盘',
            icon: 'emicon-rizhichakan',
            code: 'sub_menu_dashboard',
            url: '/deploycenter/monitoring/dashboard',
            level: 'three',
            routers: [],
            children: [],
          },
          {
            title: '告警',
            icon: 'emicon-shijianzhenduan',
            code: 'sub_menu_alert',
            url: '/deploycenter/monitoring/alert',
            level: 'three',
            routers: [],
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: '平台管理',
    icon: 'emicon-yingyongguanli',
    code: 'menu_platform_manager',
    url: '/platform',
    level: 'first',
    routers: ['/platform/scriptManager', '/platform/backup', '/platform/clusterInspection'],
    children: [
      {
        title: '备份配置',
        icon: 'emicon-shijianzhenduan',
        code: 'sub_menu_configuration_backup_config',
        url: '/platform/backup',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '脚本管理',
        icon: 'emicon-yunweijiaobenpingtaibeifen',
        code: 'sub_menu_platform_manager_scriptManager',
        url: '/platform/scriptManager',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '集群巡检',
        icon: 'emicon-yunweijiaobenpingtaibeifen',
        code: 'sub_menu_platform_manager_cluster_inspection',
        url: '/platform/clusterInspection',
        level: 'second',
        routers: [],
        children: [],
      },
    ],
  },
  {
    title: '系统配置',
    icon: '',
    code: 'menu_system_configuration',
    url: '/systemconfig',
    level: 'first',
    routers: ['/systemconfig/security', '/systemconfig/globalConfig'],
    children: [
      {
        title: '平台安全',
        icon: 'emicon-jiankonggaojing2',
        code: 'sub_menu_configuration_platformsecurity_config',
        url: '/systemconfig/security',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '全局配置',
        icon: 'emicon-shijianzhenduan',
        code: 'sub_menu_configuration_platformsecurity_config_view',
        url: '/systemconfig/globalConfig',
        level: 'second',
        routers: [],
        children: [],
      },
    ],
  },
  {
    title: '用户管理',
    icon: '',
    code: 'menu_user_manage',
    url: '/usercenter',
    level: 'first',
    routers: [
      '/usercenter/members',
      '/usercenter/role',
      '/usercenter/role/view',
      '/usercenter/selfinfo',
      '/usercenter/audit',
    ],
    children: [
      {
        title: '成员管理',
        icon: 'emicon-chengyuanguanli',
        code: 'sub_menu_user_manage',
        url: '/usercenter/members',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '角色管理',
        icon: 'emicon-jiaoseguanli',
        code: 'sub_menu_role_manage',
        url: '/usercenter/role',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '个人信息',
        icon: 'emicon-gerenxinxi',
        code: 'sub_menu_user_info',
        url: '/usercenter/selfinfo',
        level: 'second',
        routers: [],
        children: [],
      },
      {
        title: '安全审计',
        icon: 'emicon-shenji',
        code: 'menu_security_audit',
        url: '/usercenter/audit',
        level: 'second',
        routers: [],
        children: [],
      },
    ],
  },
];

export const clusterNavData = [
  {
    title: '总览',
    icon: 'emicon-gailan',
    code: 'sub_menu_detail_overview',
    isShow: true,
    key: 'index',
  },
  {
    title: '主机资源',
    icon: 'emicon-fuwu',
    code: 'sub_menu_detail_host',
    isShow: true,
    key: 'host',
  },
  {
    title: '镜像仓库',
    icon: '',
    code: 'sub_menu_detail_image_store',
    isShow: true,
    key: 'imagestore',
  },
  {
    title: '命名空间',
    icon: '',
    code: 'sub_menu_detail_namespace',
    isShow: true,
    key: 'namespace',
  },
  {
    title: '已部署组件',
    icon: '',
    code: 'sub_menu_detail_deployed',
    isShow: true,
    key: 'deployed',
  },
  {
    title: '部署历史',
    icon: '',
    code: 'sub_menu_detail_history',
    isShow: true,
    key: 'history',
  },
  {
    title: '补丁包',
    icon: '',
    code: 'sub_menu_detail_patch',
    isShow: true,
    key: 'patchHistory',
  },
  {
    title: '集群命令',
    icon: '',
    isShow: true,
    key: 'echoList',
  },
  {
    title: '集群命令详情',
    icon: '',
    isShow: false,
    key: 'echoDetail',
  },
];
