// Licensed to Apache Software Foundation(ASF) under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Apache Software Foundation(ASF) licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseWorkLoad) DeepCopyInto(out *BaseWorkLoad) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseWorkLoad.
func (in *BaseWorkLoad) DeepCopy() *BaseWorkLoad {
	if in == nil {
		return nil
	}
	out := new(BaseWorkLoad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessStatus) DeepCopyInto(out *ProcessStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessStatus.
func (in *ProcessStatus) DeepCopy() *ProcessStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceWorkload) DeepCopyInto(out *ServiceWorkload) {
	*out = *in
	in.WorkLoad.DeepCopyInto(&out.WorkLoad)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceWorkload.
func (in *ServiceWorkload) DeepCopy() *ServiceWorkload {
	if in == nil {
		return nil
	}
	out := new(ServiceWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoad) DeepCopyInto(out *WorkLoad) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoad.
func (in *WorkLoad) DeepCopy() *WorkLoad {
	if in == nil {
		return nil
	}
	out := new(WorkLoad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkLoad) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadList) DeepCopyInto(out *WorkLoadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkLoad, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadList.
func (in *WorkLoadList) DeepCopy() *WorkLoadList {
	if in == nil {
		return nil
	}
	out := new(WorkLoadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkLoadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPart) DeepCopyInto(out *WorkLoadPart) {
	*out = *in
	in.BaseWorkLoad.DeepCopyInto(&out.BaseWorkLoad)
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]WorkLoadPartStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPart.
func (in *WorkLoadPart) DeepCopy() *WorkLoadPart {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPartStatus) DeepCopyInto(out *WorkLoadPartStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPartStatus.
func (in *WorkLoadPartStatus) DeepCopy() *WorkLoadPartStatus {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPartStep) DeepCopyInto(out *WorkLoadPartStep) {
	*out = *in
	in.Object.DeepCopyInto(&out.Object)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPartStep.
func (in *WorkLoadPartStep) DeepCopy() *WorkLoadPartStep {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPartStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadSpec) DeepCopyInto(out *WorkLoadSpec) {
	*out = *in
	if in.WorkLoadParts != nil {
		in, out := &in.WorkLoadParts, &out.WorkLoadParts
		*out = make([]WorkLoadPart, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadSpec.
func (in *WorkLoadSpec) DeepCopy() *WorkLoadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkLoadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadStatus) DeepCopyInto(out *WorkLoadStatus) {
	*out = *in
	if in.PartStatus != nil {
		in, out := &in.PartStatus, &out.PartStatus
		*out = make(map[string]WorkLoadPartStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadStatus.
func (in *WorkLoadStatus) DeepCopy() *WorkLoadStatus {
	if in == nil {
		return nil
	}
	out := new(WorkLoadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProcess) DeepCopyInto(out *WorkloadProcess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProcess.
func (in *WorkloadProcess) DeepCopy() *WorkloadProcess {
	if in == nil {
		return nil
	}
	out := new(WorkloadProcess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadProcess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProcessList) DeepCopyInto(out *WorkloadProcessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadProcess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProcessList.
func (in *WorkloadProcessList) DeepCopy() *WorkloadProcessList {
	if in == nil {
		return nil
	}
	out := new(WorkloadProcessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadProcessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProcessSpec) DeepCopyInto(out *WorkloadProcessSpec) {
	*out = *in
	if in.WorkLoads != nil {
		in, out := &in.WorkLoads, &out.WorkLoads
		*out = make(map[string]ServiceWorkload, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProcessSpec.
func (in *WorkloadProcessSpec) DeepCopy() *WorkloadProcessSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadProcessSpec)
	in.DeepCopyInto(out)
	return out
}
