/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'chengyingDocs'}],
  roadmap: [{type: 'autogenerated', dirName: 'roadmap'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  docs: [
    'chengyingDocs/intro',
    'chengyingDocs/quickstart',
    {
      type: 'category',
      label: '功能介绍',
      items: [
          "chengyingDocs/introduction/install",
          "chengyingDocs/introduction/cluster",
          "chengyingDocs/introduction/clusterService",
          "chengyingDocs/introduction/monitor",
          "chengyingDocs/introduction/schema",
          "chengyingDocs/introduction/commonUpgrade",
          "chengyingDocs/introduction/smoothUpgrade",
          "chengyingDocs/introduction/productLine",
      ]
    },

    'chengyingDocs/contributing',
    'chengyingDocs/faq',
    // {
    //   type: 'category',
    //   label: 'Connectors',
    //   link: {
    //     type: 'generated-index',
    //   },
    //   collapsed: false,
    //   items: [
    //     'installation',
    //     'configuration',
    //     'playground',
    //     'typescript-support',
    //   ],
    // },
  ]
};

module.exports = sidebars;
