FROM debian:buster-slim
COPY easykube /easykube/
COPY example-config.yml /easykube/
RUN set -x && \
         echo "deb http://mirrors.aliyun.com/debian/ buster main non-free contrib" > /etc/apt/sources.list && \
         echo "deb-src http://mirrors.aliyun.com/debian/ buster main non-free contrib" >> /etc/apt/sources.list && \
         apt-get update && apt-get install -y --no-install-recommends \
         vim \
         ssh \
         ca-certificates \
         && \
         apt-get clean && \
         rm -rf /var/lib/apt/lists/* && \
         ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
         chmod a+x /easykube/easykube
WORKDIR /easykube
EXPOSE 8899

CMD ["./easykube","-c","example-config.yml","--debug"]

